### ISSUE TITLE
inconsistency with versioning configuration

### ISSUE THREAD

**Issue by ThomasJejkal** [kit-data-manager/repo-core#4]
**Describe the bug**
In `application.properties` there are two properties enabling versioning features: `repo.audit.enabled` for enabling versioning of metadata entities, and `repo.file.versioning.default` for setting the file versioning method. Currently, `repo.audit.enabled` is not evaluated directly, but set `true` if `repo.file.versioning.default` is set to a value different from `none`. 

**To Reproduce**
1. Open `application.properties`
2. Set `repo.audit.enabled:true`
3. Set `repo.file.versioning.default:none`
4. Start the service
5. Create and update a resource on the metadata level

**Expected behavior**
According to the configuration, the resource should be available in two versions: the created one and the modified one, accessible both using the `?version=` query parameter. Instead, providing the version parameter always returns HTTP 404, whereas omitting the version parameter returns the current state.

**Suggested Solution**
I see two options: 

1. Allow independent enabling of versioning for metadata and data (behavior before repo-core). If versioning of data is disabled, files can be overwritten, e.g., via `?force` query parameter as it is done in base-repo. This would allow to avoid unexpected growth of data for use cases with very huge datasets, but keeps the possibility to track changes on the administrative metadata. On the other hand, if there are no such use cases for a service based on repo-core, e.g., for metastore2, this option might be confusing.
2.  Remove the property `repo.audit.enabled` and enable versioning based on the file versioning setup (current behavior in repo-core). The question in that case is, whether overwriting files (without updating the version) should be allowed via `?force` parameter.

**Comment by VolkerHartmann** [comment]
**To avoid additional confusion:**
application.properties is **not** part of repo-core.
It's part of the tests due to avoid inconsistencies to the former code which was part of the base-repo. 
(by the way: when repo-core has a fixed interface (and this issue shows that the interface is still under discussion) 
this test code should be removed) 
The configuration (e.g. via application.properties) should be done by the service and set the attributes of RepoBaseConfiguration accordingly. 
Nevertheless the property 'auditEnabled' is a kind of senseless right now as the versioning setup will be done via the selected versioning service. As a matter of this the property 'auditEnabled' cannot be set from a service using repo-core.
 Two versioning services are available right now: 
- none   - which disables versioning  and
- simple - which adds another copy for the versioned file.

**Another Suggested Solution**
I see a third option:
3. As the property  'auditEnabled' is not configurable/writable right now services build on repo-core can't use this feature. Therefore there is no urgent need to act. Which, of course, does not apply to base-repo.

--> If there is any use case described by the first solution there should be a feature request.

**Comment by ThomasJejkal** [comment]
In base-repo, I declared repo.audit.enabled as unused and removed all checks. Issue will be closed.
